version: '3.8'

# Definición de Docker Secrets
secrets:
  influx_admin_password_secret:
    file: ${INFLUX_ADMIN_PASSWORD_FILE}
  influx_write_token_secret:
    file: ${INFLUX_WRITE_TOKEN_FILE}

services:
  # -------------------------------------------------------
  # 1. NODE-RED
  # -------------------------------------------------------
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    environment:
      # Carga TZ desde .env
      - TZ=${TZ}
    volumes:
      - ./node-red/data:/data
    restart: unless-stopped
    networks:
      - red-practica1-sbd
    secrets:
      - influx_write_token_secret
    # El token estará disponible en /run/secrets/influx_write_token_secret

  # -------------------------------------------------------
  # 2. INFLUXDB
  # -------------------------------------------------------
  influxdb:
    image: influxdb:2.7.12-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      # Carga variables de configuración desde .env
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      # Referencia al secreto para la contraseña de configuración inicial
      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influx_admin_password_secret
    restart: unless-stopped
    depends_on:
      - node-red
    networks:
      - red-practica1-sbd
    secrets:
      - influx_admin_password_secret

  # -------------------------------------------------------
  # 3. GRAFANA
  # -------------------------------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - user=admin
    volumes:
      - './grafana:/var/lib/grafana'
    networks:
      - red-practica1-sbd
    depends_on:
      - influxdb

networks:
  red-practica1-sbd:
